name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main # Replace with your default branch name if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.14.0' # Use the latest LTS version of Node.js

    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build --prod

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/portfolio/browser # Matches the outputPath in your angular.json
